# Contour HTTPProxy is an alternative to Kubernetes Ingress.
# Bring your own HTTPProxy.
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: example
spec:
  virtualhost:
    fqdn: example-service.jlandowner.com
    tls:
      secretName: example-service-cert
    # The following is the definition of external authorizer.
    authorization:
      extensionRef:
        name: envoy-ext-authz-line
        namespace: envoy-ext-authz-line
  routes:
  - services:
    - name: example-service
      port: 80