apiVersion: v1
kind: Service
metadata:
  name: envoy-ext-authz-line
  namespace: envoy-ext-authz-line
spec:
  ports:
  - name: https
    port: 9443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-ext-authz-line
  namespace: envoy-ext-authz-line
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: ghcr.io/jlandowner/envoy-ext-authz-line:latest
        imagePullPolicy: IfNotPresent
        name: envoy-ext-authz-line
        args:
        - --port=9443
        - --insecure
        ports:
        - containerPort: 9443
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 9443
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 20
