apiVersion: v1
kind: Namespace
metadata:
  name: envoy-ext-authz-line
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-ext-authz-line
  namespace: envoy-ext-authz-line
spec:
  selector:
    app: envoy-ext-authz-line
  ports:
  - name: grpc
    port: 9443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-ext-authz-line
  namespace: envoy-ext-authz-line
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-ext-authz-line
  template:
    metadata:
      labels:
        app: envoy-ext-authz-line
    spec:
      containers:
      - image: ghcr.io/jlandowner/envoy-ext-authz-line:latest
        imagePullPolicy: IfNotPresent
        name: envoy-ext-authz-line
        args:
        - --line-client-id=YOUR_CLIENT_ID
        - --port=9443
        - --debug
        - --insecure
        ports:
        - containerPort: 9443
          name: grpc
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 9443
          initialDelaySeconds: 15
          periodSeconds: 20
